### ISSUE TITLE
Accompanying demo repo not public

### ISSUE THREAD

**Issue by apttie** [cosmoconsult/D365BC-Blob-Storage-API#33]
Good evening.  I enjoyed watching your Dynamics Con presentation and reading the blog post.  This repo is very useful, but it may be improved by access to the demo code (advertised in the presentation as https://dev.azure.com/DynamicsCon21-AzBlobStorage/ ).

Is it possible for you to make that repo public or otherwise make it available to us?  Thank you.

**Comment by SimonOfHH** [comment]
Hi @apttie 
Thanks for creating this issue. You'll need to access the specific project directly (which is public) e.g. via this link: https://dev.azure.com/DynamicsCon21-AzBlobStorage/Session%20Demos

I just tested it and it can be accessed also InPrivate-session of a browser. If you just try to open the organization (like with your link) you won't have access.

I think I used the wrong (or incomplete) link in my presentation 😱 Sorry for that.
